name: Mavlink Server Test TCP/UDP

on: [push, pull_request]

jobs:
  test-mavlink-server:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "UDP Test"
            server_endpoints: "udpout:127.0.0.1:14550 udpin:127.0.0.1:14551"
            client_endpoints: "udpin:127.0.0.1:14550 udpout:127.0.0.1:14551"
          - name: "TCP Test"
            server_endpoints: "tcpout:127.0.0.1:5761 tcpin:127.0.0.1:5760"
            client_endpoints: "tcpin:127.0.0.1:5761 tcp:127.0.0.1:5760"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install build dependencies - Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile minimal --target x86_64-unknown-linux-musl,wasm32-unknown-unknown -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install build dependencies - Cargo-Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install build dependencies - Trunk
        run: cargo binstall -y trunk

      - name: Building frontend (wasm32)
        working-directory: src/webpage
        run: trunk build --release --locked --verbose

      - name: Build mavlink-server
        run: |
          cargo build --release --locked

      - name: Run mavlink-server
        run: |
          ./target/release/mavlink-server ${{ matrix.server_endpoints }} &
          sleep 5

      - name: Run Python Heartbeat Test
        run: |
          cd tests/scripts
          uv run test_heartbeat.py ${{ matrix.client_endpoints }}
